spring:
  application:
    name: bookhub
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bookhub_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: 3821282770444b39732138203642275b516a7849204b3f306e356a6526
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /bookhub/api